#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:rhel_9_golang_1.23)
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.23 AS builder

COPY --chown=1001:0 . /workspace
WORKDIR /workspace/
ENV GOEXPERIMENT strictfipsruntime
RUN CGO_ENABLED=1 GOOS=linux go build -v -mod=mod -tags strictfipsruntime -o /workspace/bin/velero-plugin-for-aws ./velero-plugin-for-aws

#@follow_tag(registry.redhat.io/ubi9/ubi-minimal:latest)
FROM registry.redhat.io/ubi9/ubi-minimal:latest
RUN microdnf -y install openssl && microdnf -y reinstall tzdata && microdnf clean all
RUN mkdir /plugins
COPY --from=builder /workspace/bin/velero-plugin-for-aws /plugins/
USER 65534:65534
ENTRYPOINT ["/bin/bash", "-c", "cp /plugins/* /target/."]

LABEL \
        com.redhat.component="oadp-velero-plugin-for-aws-container" \
        version="1.5.0" \
        name="oadp/oadp-velero-plugin-for-aws-rhel9" \
        License="Apache License 2.0" \
        io.k8s.display-name="OADP Velero Plugin for AWS" \
        io.openshift.tags="migration" \
        io.k8s.description="OpenShift API for Data Protection - Velero Plugin for AWS" \
        io.openshift.build.commit.id="bc46728f62fbc70e0bb689491ea55dad229dccc5" \
        io.openshift.build.source-location="https://github.com/openshift/velero-plugin-for-aws" \
        io.openshift.build.commit.url="https://github.com/openshift/velero-plugin-for-aws/commit/bc46728f62fbc70e0bb689491ea55dad229dccc5" \
        summary="OpenShift API for Data Protection - Velero Plugin for AWS" \
        maintainer="OpenShift API for Data Protection Team <oadp-team@redhat.com>"
